### ISSUE TITLE
Instruction.semantics should be renamed

### ISSUE THREAD

**Issue by mossberg** [trailofbits/pyevmasm#13]
I don't think `.semantics` is exactly the optimal name for this member of the Instruction class, i think a better name might be `.mnemonic`. 

this would be an api breaking change.

**Comment by feliam** [comment]
From a quick look on definitions...
mnemonics: a system such as a pattern of letters, ideas, or associations which assists in remembering something.
semantics: the meaning and interpretation of words, signs, and sentence 

What would be the mnemonic for "PUSH32".  ?  PUSH?

**Comment by mossberg** [comment]
maybe just PUSH32? All the different push instructions are technically
different instructions with different semantics, so I'm not sure they
should share a mnemonic even though it's very similar..?



I  also think mnemonic is fairly common in other disassemblers?

**Comment by feliam** [comment]
https://github.com/trailofbits/pyevmasm/blob/master/pyevmasm/evmasm.py#L337

**Comment by feliam** [comment]
So there is already a `.mnemonic` that does what you want. 
```
    @property
    def mnemonic(self):
        """ Alias for name """
        return self.name
```

Should we close this or do you have a proposal for renaming `semantics` to something else? 

Note it should capture the basic semantic meaning of the instructions (mostly for the ones that have several sizes but do the same thing) SWAP, PUSH, LOG

**Comment by mossberg** [comment]
> So there is already a `.mnemonic` that does what you want.
ah I see. Sorry, I should have looked more carefully then :( closing!
