### ISSUE TITLE
UnknownMnemonicError MSTORE

### ISSUE THREAD

**Issue by meyira** [trailofbits/pyevmasm#18]
I tried assembling a few files that I got by compiling solidity with --asm. When assembling them in pyevmasm, I'm getting `pyevmasm.evmasm.UnknownMnemonicError: MSTORE(0X40,`
as well as 
```
File "/usr/lib/python3.7/site-packages/pyevmasm/evmasm.py", line 594, in assemble_all
    instr = assemble_one(line, pc=pc)
  File "/usr/lib/python3.7/site-packages/pyevmasm/evmasm.py", line 561, in assemble_one
    raise Exception("Something wrong at pc %d" % pc)
Exception: Something wrong at pc 0
```
Is it possible that these Mnemonics are not implemented, and if they are, how can I assemble the file? 
Thanks

**Comment by disconnect3d** [comment]
Can you attach a minimal [not] working example here?

**Comment by meyira** [comment]
Yes, I have a couple. 
This is from the assembly from the not so smart contracts: 
```
sub_0: assembly {
        /* "Unprotected.sol":26:503  contract Unprotected{... */
      mstore(0x40, 0x80)
      jumpi(tag_1, lt(calldatasize, 0x4))
      calldataload(0x0)
      0x100000000000000000000000000000000000000000000000000000000
      swap1
      div
      0xffffffff
      and
      dup1
      0x9d87b813
      eq
      tag_2
```

and here, from the underhanded solidity contract. 
```
sub_0: assembly {
        /* "Unprotected.sol":26:503  contract Unprotected{... */
      mstore(0x40, 0x80)
      jumpi(tag_1, lt(calldatasize, 0x4))
      calldataload(0x0)
      0x100000000000000000000000000000000000000000000000000000000
      swap1
      div
      0xffffffff
      and
      dup1
      0x9d87b813
      eq
      tag_2

```

Amongst both, evmasm does not parse mstore ( raise UnknownMnemonicError(item)
pyevmasm.evmasm.UnknownMnemonicError: MSTORE(0X40,
)

**Comment by computerality** [comment]
Hi meyira, pyevmasm only supports assembling EVM, not YUL.
You would want to convert something like `mstore(0x40, 0x80)` to
```
PUSH1 0x80
PUSH1 0x40
MSTORE
```
